name: lint_javascript

on:
  push:
    branches:
    - main
  pull_request:
    paths:
      - .babelrc
      - .mocharc.js
      - app/**.js
      - bulk-decaffeinate.config.js
      - cli/**.js
      - config/**.js
      - desktop/**.js
      - gulp/**.js
      - gulpfile.babel.js
      #- packages/**.js
      - scripts/**.js
      - server/**.js
      - test/**.js
      - worker/**.js

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v3

    - name: install system dependencies
      run: sudo apt-get install -y libpng-dev

    - name: install node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Caching node_modules saves 50s on builds which don't modify dependencies.
    # Compared to yarn caching, it saves an additional 27 seconds.
    - name: cache node_modules
      uses: actions/cache@v3
      with:
        path: /home/runner/work/duelyst/duelyst/node_modules
        key: node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          node-modules-

    - name: redirect git ssh to https
      run: |
        git config --global url."https://github.com/".insteadOf git@github.com:
        git config --global url."https://".insteadOf git://

    - name: install node dependencies
      run: yarn install --dev

    - name: compile typescript dependencies
      run: yarn tsc:chroma-js

    - name: lint javascript code
      run: yarn lint:js:all
